name: alexandrio_app
description: Alexandrio Crossplatform Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  html: any
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_ui_tools:
    git: git@github.com:williambulin/flutter_ui_tools
  dart_discord:
    git: git@github.com:williambulin/dart_discord
  epubx: any
  epub_view: any
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # file_picker: ^3.0.1
  file_picker_cross: ^4.3.2
  syncfusion_flutter_pdf: ^18.3.53-beta

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  pedantic: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/samples/
    - assets/samples/pdf/
    - assets/samples/epub/
