name: alexandrio_app
description: Alexandrio Crossplatform Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  hive: any
  hive_flutter: any
  flutter_ui_tools:
    path: C:/Users/OrangeCat/Desktop/Projects/Personal/flutter_ui_tools

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.13

flutter:
  uses-material-design: true
  assets:
    - assets/
