name: demo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  pdf: any
  printing: any
  file_picker: any
  file_selector: any
  file_selector_macos:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/file_selector/file_selector_macos
  file_selector_linux:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/file_selector/file_selector_linux
  file_selector_windows:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/file_selector/file_selector_windows
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  printing:
    git:
      url: https://github.com/alexandr-io/dart_pdf
      path: printing
  pdf:
    git:
      url: https://github.com/alexandr-io/dart_pdf
      path: pdf
  extended_image: 1.5.0-dev

flutter:
  uses-material-design: true
  assets:
    - assets/
