name: Flutter Build

on:
  push:
  # pull_request:  # enable if repo goes public
  release:
    types: [published]

jobs:
  build:
    defaults:
      shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            OS_NAME: linux
            MOBILE_BUILD: true
            MOBILE_NAME: android
            MOBILE_TARGET: apk
            MOBILE_ARGS: ""
          - os: macos-latest
            MOBILE_BUILD: true
            OS_NAME: macos
            MOBILE_NAME: ios
            MOBILE_TARGET: ios
            MOBILE_ARGS: "--no-codesign"
          - os: windows-latest
            OS_NAME: windows
            MOBILE_BUILD: false
            MOBILE_NAME: ""
            MOBILE_TARGET: ""
            MOBILE_ARGS: ""

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1  # https://github.com/marketplace/actions/flutter-action
      with:
        channel: 'master'
    - run: flutter config --enable-${{matrix.OS_NAME}}-desktop
    - run: flutter config --enable-${{matrix.MOBILE_NAME}}
      if: matrix.MOBILE_BUILD
    - run: flutter pub get
    - run: flutter test
    - run: flutter build --no-pub ${{matrix.OS_NAME}}
    - run: flutter build --no-pub ${{matrix.MOBILE_TARGET}} ${{matrix.MOBILE_ARGS}}
      if: matrix.MOBILE_BUILD

    # TODO: Upload bins and publish in releases
