name: Flutter Build

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop
  pull_request:
    branches:
      - main
      - master
      - dev
      - develop
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: ["apk", "ios", "windows", "linux", "macos"]
        include:
          - target: apk
            os: ubuntu-20.04
            OS_NAME: linux
            ACTION_NAME: "Android"
            ENABLE: "--enable-android"
            ARGS: ""  # for store release, use "--target-platform android-arm,android-arm64,android-x64 --split-per-abi"

          - target: ios
            os: macos-10.15
            OS_NAME: macos
            ACTION_NAME: "iOS"
            ENABLE: "--enable-ios"
            ARGS: "--no-codesign"

          - target: windows
            os: windows-2019
            OS_NAME: windows
            ACTION_NAME: "Desktop Windows"
            ENABLE: "--enable-windows-desktop"
            ARGS: ""

          - target: linux
            os: ubuntu-20.04
            OS_NAME: linux
            ACTION_NAME: "Desktop Linux"
            ENABLE: "--enable-linux-desktop"
            ARGS: ""

          - target: macos
            os: macos-10.15
            OS_NAME: macos
            ACTION_NAME: "Desktop MacOS"
            ENABLE: "--enable-macos-desktop"
            ARGS: ""

    runs-on: ${{matrix.os}}
    name: ${{matrix.ACTION_NAME}}

    steps:
    - name: Install Dependencies
      run: sudo apt install -y ninja-build libgtk-3-dev
      if: matrix.target == 'linux'

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1  # https://github.com/marketplace/actions/flutter-action
      with:
        channel: 'dev'  # 'master' doesn't work somehow, gotta do it manually...

    - name: Switch Flutter channel
      run: flutter channel master && flutter upgrade

    - name: Cleanup workspace
      run: flutter clean

    - name: Configure Flutter
      run: |
        flutter config ${{matrix.ENABLE}}
        flutter create .
        flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build
      run: flutter build ${{matrix.target}} ${{matrix.ARGS}}

    # tmp
    - name: List build directory
      run: find build
      if: always()

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ env.RELEASE_NAME }}
    #     path:
    #     retention-days: 7
    #     if-no-files-found: error

    # - name: Upload Artifact to Release
    #   uses: actions/upload-release-asset@v1.0.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #       upload_url: ${{ github.event.release.upload_url }}
    #       asset_path:
    #       asset_name:
    #       asset_content_type: 
    #   if: github.event_name == 'release' && github.event.action == 'published'
