name: Flutter Build

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop
  pull_request:
    branches:
      - main
      - master
      - dev
      - develop
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: ["apk", "ios", "windows", "linux", "macos"]
        include:
          - target: apk
            os: ubuntu-20.04
            OS_NAME: linux
            ACTION_NAME: "Android"
            ENABLE: "--enable-android"
            ARGS: ""  # for store release, use "--target-platform android-arm,android-arm64,android-x64 --split-per-abi"
            ARTIFACT_PATH: "build/app/outputs/flutter-apk/app-release.apk"
            ARTIFACT_NAME: "Release-Android"

          - target: ios
            os: macos-10.15
            OS_NAME: macos
            ACTION_NAME: "iOS"
            ENABLE: "--enable-ios"
            ARGS: "--no-codesign"
            ARTIFACT_PATH: "build/ios/Release-iphoneos/Runner.app"
            ARTIFACT_NAME: "Release-iOS"

          - target: windows
            os: windows-2019
            OS_NAME: windows
            ACTION_NAME: "Desktop Windows"
            ENABLE: "--enable-windows-desktop"
            ARGS: ""
            ARTIFACT_PATH: "build/windows/runner/Release"
            ARTIFACT_NAME: "Release-Windows"

          - target: linux
            os: ubuntu-20.04
            OS_NAME: linux
            ACTION_NAME: "Desktop Linux"
            ENABLE: "--enable-linux-desktop"
            ARGS: ""
            ARTIFACT_PATH: "build/linux/release/bundle"
            ARTIFACT_NAME: "Release-Linux"

          - target: macos
            os: macos-10.15
            OS_NAME: macos
            ACTION_NAME: "Desktop MacOS"
            ENABLE: "--enable-macos-desktop"
            ARGS: ""
            ARTIFACT_PATH: "build/macos/Build/Products/Release/alexandrio_app.app"
            ARTIFACT_NAME: "Release-MacOS"

    runs-on: ${{matrix.os}}
    name: ${{matrix.ACTION_NAME}}

    steps:
    - name: Install Dependencies
      run: sudo apt install -y ninja-build libgtk-3-dev
      if: matrix.target == 'linux'

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1  # https://github.com/marketplace/actions/flutter-action
      with:
        channel: 'dev'  # 'master' doesn't work somehow, gotta do it manually...

    - name: Switch Flutter channel
      run: flutter channel master && flutter upgrade

    - name: Cleanup workspace
      run: flutter clean

    - name: Configure Flutter
      run: |
        flutter config ${{matrix.ENABLE}}
        flutter create .
        flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build
      run: flutter build ${{matrix.target}} ${{matrix.ARGS}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.ARTIFACT_NAME }}
        path: ${{ matrix.ARTIFACT_PATH }}
        retention-days: 7
        if-no-files-found: error
    
    - name: Prepare for Release
      run: ./ci/prepare_release.sh ${{ matrix.TARGET }} ${{ matrix.ARTIFACT_NAME }} ${{ matrix.ARTIFACT_PATH }}
      # if: github.event_name == 'release' && github.event.action == 'published'

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: ${{ matrix.ARTIFACT_NAME }}.zip
          asset_path: ${{ matrix.ARTIFACT_PATH }}
          asset_content_type: application/zip
      if: github.event_name == 'release' && github.event.action == 'published'
